apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy-deployment
  namespace: ntfy
  labels:
    app: ntfy-deployment
spec:
  selector:
    matchLabels:
      app: ntfy-pod
  template:
    metadata:
      labels:
        app: ntfy-pod
    spec:
      containers:
        - name: ntfy
          image: binwiederhier/ntfy:v1.28.0
          env:
            - name: TZ
              value: Europe/Berlin
            - name: NTFY_DEBUG
              value: "false"
            - name: NTFY_LOG_LEVEL
              value: INFO
            - name: NTFY_BASE_URL
              value: ntfy.feleuxens.de
          resources:
            limits:
              memory: 300Mi
              cpu:  200m
            requests:
                  cpu: 150m
                  memory: 150Mi
