apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./apps/ntfy
patches:
  - path: ingress.yaml
    target:
      kind: Ingress
  - path: deployment.yaml
    target:
      kind: Deployment