apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - sealed-db-secrets.yaml
  - sealed-secrets.yaml