---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    password: AgAR4fj+keMpUy+aT0TILOMt3Fa+oVumVaIq520SthdYGMI4wu99qdLoVKKeNs2vTiD/QO8DTmvW1DR9IDRqoMF+zR6/MEfP56G1hTRWwG7ZZP1a+KxhRohwuU8vSWW0H6iPVoNUsoKl6NIvPHr4fpxyCzBoby61wCHr9BrBXQrqg9vrSqMTMOKkL4d1OSiugEmiuGlhiv5sK7yN3XB9Au1vk7s5KNVrQ0UXT6cdlZt+z/om5fsobhj/75CIiJvWSDyToym2pJu2dICma4wyH8FEZVRhfI/eBZfT2Le0h2pQDSkIKax/70Jcs9lhFmeIxSWd67lrzhBZHsz4LbOka8FetAGJhIM1eoaK3nDhZdsgzXgQ8INH+G02WmMTqU20faDP9D/uPOZ1QT6qBrh4Xdjc56gqZN+GUXeMEH9S1Rjjjschq6Yd171eCRR6FG6heBwmGGmPWVqOQyp3cCegB3M+4gL3MyJz6iKT940koFan727dRm7WCqaOjUOtLoJ2pKVCgddY5qU6Y1Fol93LKqqpsDkbTx3rASwP/LyC+1tZiI4UPg/WBEJcRYtDGsdE+ogBhzwMTXLc5AicfC10WOYf/IYm/XWMOR2feZCwqSmHUwiNh0hcBQJZni+CwgD0IvLU6SUmoMCcVrT3KjIIRtZ35jGBWJFYaM74wT23RlXQggQurGGRvy1r2ZWtF/bk0ZI/5bhHNdB9ZivS7hH5M+RDg3niHLeNF3kA8+Z1PcYkt0sYvQxcT7z1Ea/4ovyIHEyvaeh/AKAb68r7nrI=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin
      namespace: keycloak
