---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db
  namespace: keycloak
spec:
  encryptedData:
    password: AgCL17Hc/A1ydEukci30LCirQqIIaqr6w5XXvMByd8yODIRHIVc79au3w6WVTeBfuPMf3RMAwRyrvv7XioQTN1dAS/8kvW8ux6w2aOanJIEDlROilftarZzeLFaFPfzaxyYrTpFZsUj3bZyxmh+vtmG5OWHyi+HeMUauXiZDPvHJxECnYUzcI9yk2UJvQpglUHcca+nc3LVJNa1FZqeN5qOouDMIzv9q1xArxxNfneWcMW0WZIJC1Q5Dtkh1QgHwrBurKYj5X2TNrcSt5fsyFaBre3IlfTOsyu24T1hdSrjTn3XkD5IQVTIqvchP0iG6MGH01UadMEtwVpFqST44gYfxbD/Jdfnt4bwxipE6jGZNAJG4yGdZbT9pBu9AhQIisgSlJqXYql2v86f35nhKFzXae0oKijKEqZ22oDRA2f1t10lLgQb8yXynNUb6jYBCjPQdI09NNx7/sOe7m0LbTSmztbC1ttfDaLYdfPtkx8Eu8SHLC/vT+Vqw59a9mcF9cIJqNzC6vHw/7Zk32x3YPGlBCFHebM2fw1stxsW0qhJ+PCJGnnaHBGLJD4CsR95k0d3zb7HR3DSFWd/eOazFR3FKRlbu2cBbe2bsLOPs9bCdjhOLUUJuyKCs5VNqobBRDsr10G4aAk/5NyXfTtDv9+InYSjWuGQZZfvnDdUMcFvKSWGU6KLdsXukkJhsAS94I3Xt2wPTeaf0aOQAbIPy8mWK0o/+IXCt4743TND0Sms=
    postgres-password: AgCPjeMuAaBZW4Ob51DfOsWGYeNC8veoGqbsLDxwp8UrS5imxdl6O9jyMBCYD8iD6sJOb8f6zTXQZtf+LRQFGyZjt9o3f6R1CMLTMhth84hCuojCdDwVgsb+kSkfTm+YDmDMpE8h1BIyMN5HOZFeNwJAIGImRuVvshev+1UsaRP6UaaUHDjESaVI6HB42hMZxe23RWUWr27MJZqKYt+jdh+eZkWBktTHQ7f/OPyEfeneeUdabqd4//LOkpX51Z5Hgk5hDBgeqxVX9yKFtczvITXqYfIpQrl+n+ASZC3vjpXYwps7LXIg0l+yf+4nE6QzEL68AYjZ1FrBcIcwV4bonwdpEduMyjn58AEMZwowJDZgzWZ0r2EG/EhHRQm3fB0eATfsf9Wd/zuqRelIzNe+nusRzaI4LAs0AEukQC7WeRf1v0JVTrzDEakYP4sGfHajL1PsYwxpUIQI+3p1RtBGHhdWepOCqtEUtKpQ2mMryMZslZO+j1wG805EtACNY1ciZ/vRtYBxWibBTrCTUPjrNDg17vt6aoZbNPvwDJ81YG47hW2kAn9ppGDbue/3L0vRXJJ8nFRVQdfQTSDQ6Bf0C9G5MbqAzUb530rvZQZ1VdP0SsaN7izq+iwHzbtw8UMnZZL9OMhlTaAnMjFP3PEWTWB/tfjXHDj1FJvKswl+fmr2Pn2QmwDejCZ5mjpgVg4a2rlxcMZ/bnG/7HZmaNFY5KTwpghtE0JLciGfkNyuBrU=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-db
      namespace: keycloak
