apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - db-secret.yaml
  - admin-secret.yaml
  - ingress-redirect.yaml
  - ingress-admin.yaml