apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - svc.yaml
  - pvc.yaml
  - ingress.yaml
configMapGenerator:
    - name: server-config
      files: 
        - server.yml
namespace: ntfy