apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/nextcloud
  - sealed-secrets.yaml
  - sealed-db-secrets.yaml
patches:
  - path: values.yaml
    target:
      kind: HelmRelease