apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  chart:
    spec:
      version: 0.3.1

  values:
    server:
      ingress:
        main:
          hosts:
            - host: immich.feleuxens.de
              paths:
                - path: "/"
          tls:
            - secretName: immich-tls
              hosts:
                - immich.feleuxens.de