apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-secret
    namespace: nextcloud
data:
    mariadb-root-password: ENC[AES256_GCM,data:Q2C7PNhFXnLg+jlA1LGy4cXRACbQjkNlzesltz05CBy2lamGCqQiXA==,iv:IGNpOo9S+p1lU1bLE9NBuECm3sW+XYDjU7Y+ikRoZ3M=,tag:3M5W5gBEuxmwml3tdCscog==,type:str]
    mariabdb-replication-password: ENC[AES256_GCM,data:HofMwid/dFyl6LS2GEXdAsPs+J7k+Ct8ovrLuCAnt6c=,iv:16GDc1Jw0iUpEbhX9rr5bE6qoJFQG9kxFrKFrwpciW4=,tag:9L/aJPJUahRhkwMwhh7hbQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:ZLGqTHjlKwMQqtjIto4l0tvEWKIvh9ly0RyrDjCDJO94rk5YRLZOzw==,iv:PINOu9+tdtNbT5+oaKAE9S6n1QfJ3LN5ihTZMheVtmU=,tag:1Q6gj4odgzHp6ffoVTZPkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-11T19:11:03Z"
    mac: ENC[AES256_GCM,data:kF8AsZaeshXk76BDnD7hXcSk+JT/djfS85fDQEMdcnxfJhHoZz4l0vz48ojf8nWCQtp3zSP8CsIDSAgadDNzVRJK5d+0PT3+lVuCKxaFO/xRJKyIdMKuZejZ3l9XNIEGXN3XuEaecNjVg0JZIuhdml76a2jUDUh/eYz661XZbvQ=,iv:/+fZYqjiAe1E+RGLyV0vNHf6VeDN6qBnk9AWt1l6VWM=,tag:8xZ99JN++JQ4bCwIplenHg==,type:str]
    pgp:
        - created_at: "2024-01-11T19:11:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5qsTVicku58AQ/+MMmt51ep4wwFZ+S2Zsnqj3TfzZoGMPE31uhwffoiukmQ
            KmLjsOjL/nR7bgqiXRuKpx6gC9S7L07LbrhqveROPMC3hl8rJr8C0YbjpSQNAqdl
            SEqKVc06jCu0LgFkaauwTcl0eVaiPym05tSTM8B82MTfISGEPOoBUyCF/d/5AncE
            cKn0rxC4sJHx06AV4+hw1B5He51WfpWaRUoJXBpnIf2HC2RuBZEtVJJBYSN+wiKb
            JusAOCnTNP1J5MXCJtpkZ0UAGY5udt1HWUOUhSgtW/ymLymV94y26CZvLgVLA03Z
            /xdXPe2dvtwC3D9WLpW7YlIIzuskMVazqvKUYAp3jisY4NvXrPcBQZnLxPRk3XOy
            wJcCU1AjtXtiEDEe1pO6cX9t7R3fKko+Jt6nsyoAOAXcoH8HvWMtSYgY0V4DO7V/
            cwp0mSCBEar2k+Pret7uhfkng6NOdDnB1I8Ub3cYlEXSriCbpjfNDToOmOqXiVEt
            p8EUHv1EJoOnR4iCIXGO9bhPkbP67aN3yQY/yOAmybHplpSGafdk6ccB4/XCJA7N
            3E1QwGFkQzUTtuROrvHPC7iWkeVnifD3c/0HFVThTmaS7fmui01l+pjsiwJgmWBZ
            gnsFIC1uUcGMVlp04lkJd+iCFNwlW9yRqxfMkuD6HfAuHrAZUJ8d7LL0edeFOSXU
            aAEJAhCsnH8oEJ78H4wLsU8TiF3WY1qgva+1q5Edpar1JtiwZOebHqUNX29PTKxV
            lTJHRtmCtpAn7FSp7Agz93Yfn6z9YYEJpMK4VV9MN9zLhRBqSLH864wZptkHno68
            lpkJQKXHZeEN
            =oUtX
            -----END PGP MESSAGE-----
          fp: 0F37E3154BB16E760379E9F1373EA0F713C7E25E
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
