name: Production

on:
  workflow_dispatch:
  push:
    paths:
      - environments/production/**


jobs:
  terraform:
    uses: ./.github/workflows/terraform-apply.yml
    environment: production
    with:
      environment: production