name: "Terraform Apply"

on:
  push:
    branches:
      - main

env:
  TF_HTTP_PASSWORD: "${{ secrets.CERIUM_PROD_STATE_TOKEN }}"
  DIR: ./environments/cerium
  TF_VAR_cerium_host: ${{ vars.CERIUM_HOST }}
  TF_VAR_cerium_client_cert: ${{ secrets.CERIUM_CLIENT_CERT }}
  TF_VAR_cerium_client_key: ${{ secrets.CERIUM_CLIENT_KEY }}
  TF_VAR_cerium_cluster_ca_cert: ${{ secrets.CERIUM_CLUSTER_CA_CERT }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive
        working-directory: "${{ env.DIR }}"
      
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: "${{ env.DIR }}"
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: "${{ env.DIR }}"
      
      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color
        working-directory: "${{ env.DIR }}"