name: "Terraform Plan"

on: 
  pull_request:

env:
  TF_HTTP_PASSWORD: "${{ secrets.CERIUM_PROD_STATE_TOKEN }}"
  DIR: ./environments/cerium
  TF_VAR_cerium_host: ${{ vars.CERIUM_HOST }}
  TF_VAR_cerium_client_cert: ${{ secrets.CERIUM_CLIENT_CERT }}
  TF_VAR_cerium_client_key: ${{ secrets.CERIUM_CLIENT_KEY }}
  TF_VAR_cerium_cluster_ca_cert: ${{ secrets.CERIUM_CLUSTER_CA_CERT }}
  TF_VAR_feleuxens_cf_account: ${{ secrets.TF_VAR_FELEUXENS_CF_ACCOUNT }}
  TF_VAR_feleuxens_cf_key: ${{ secrets.TF_VAR_FELEUXENS_CF_KEY }}
  TF_VAR_feleuxens_firefly_app_key: ${{ secrets.TF_VAR_FELEUXENS_FIREFLY_APP_KEY }}
  TF_VAR_feleuxens_firefly_pgadmin4_password: ${{ secrets.TF_VAR_FELEUXENS_FIREFLY_PGADMIN4_PASSWORD }}

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive
        working-directory: "${{ env.DIR }}"
      
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: "${{ env.DIR }}"
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: "${{ env.DIR }}"
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        working-directory: "${{ env.DIR }}"