name: "Terraform Apply"

on:
  push:
    branches:
      - main

env:
  TF_HTTP_PASSWORD: "${{ secrets.FELEUXENS_DE_PROD_STATE_TOKEN }}"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color