apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 60m0s
  chart:
    spec:
      chart: immich
      sourceRef:
        kind: HelmRepository
        name: immich
  
  values:
    immich:
      persistence:
        library:
          existingClaim: immich-data
    
    postgresql:
      enabled: true
    redis:
      enabled: true
    server:
      ingress:
        main:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: immich.local
              paths:
                - path: "/"
          tls: []
            # - secretName: immich-tls
            #   hosts:
            #     - immich.local
    
    machine-learning:
      persistence:
        cache:
          type: pvc
            